// <auto-generated />
using System;
using ClickHouse.EntityFrameworkCore.Storage.Engines;
using EntityFrameworkCore.ClickHouse.TestCases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.ClickHouse.TestCases.Migrations
{
    [DbContext(typeof(ClickHouseContext))]
    [Migration("20230711152828_asd3")]
    partial class asd3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("asd", "Asdasd")
                .HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("EntityFrameworkCore.ClickHouse.TestCases.Det", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int32");

                    b.Property<byte>("MyBool")
                        .HasColumnType("UInt8");

                    b.Property<int?>("Null")
                        .HasColumnType("Int32");

                    b.HasKey("Id");

                    b.ToTable("Dets");
                });

            modelBuilder.Entity("EntityFrameworkCore.ClickHouse.TestCases.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("Int64");

                    b.Property<DateTime?>("LastStatusUpdateDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("LinkName")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<int>("MediaId")
                        .HasColumnType("Int32");

                    b.Property<string>("MediaName")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("Int32");

                    b.Property<int?>("RefererUserId")
                        .HasColumnType("Int32");

                    b.Property<long?>("Samad")
                        .HasColumnType("Int64");

                    b.HasKey("OrderId")
                        .HasAnnotation("myann", "so do");

                    b.ToTable("Order");

                    b
                        .HasAnnotation("ASSSSS", "asd")
                        .HasAnnotation("MergeTreeEngine_ClickHouse:Engine", "{\"EngineType\":\"MergeTreeEngine_ClickHouse:Engine\",\"OrderBy\":\"OrderId,MediaId\",\"PartitionBy\":null,\"PrimaryKey\":null,\"SampleBy\":null,\"Settings\":null} ");
                });
#pragma warning restore 612, 618
        }
    }
}
