// <auto-generated />
using System;
using ClickHouse.EntityFrameworkCore.Metadata;
using EntityFrameworkCore.ClickHouse.TestCases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.ClickHouse.TestCases.Migrations
{
    [DbContext(typeof(ClickHouseContext))]
    partial class ClickHouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("EntityFrameworkCore.ClickHouse.TestCases.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int64");

                    b.Property<long?>("ClickHistoryId")
                        .HasColumnType("Int64");

                    b.Property<int>("LinkId")
                        .HasColumnType("Int32");

                    b.Property<int?>("MediaId")
                        .HasColumnType("Int32");

                    b.Property<int?>("WebStoreId")
                        .HasColumnType("Int32");

                    b.HasKey("OrderId");

                    b.ToTable("Order", "Order");

                    b
                        .HasAnnotation("ClickHouseTableAttribute", "CREATE_OR_REPLACE")
                        .HasAnnotation("ReplacingMergeTreeEngine_ClickHouse:Engine", "{\"EngineType\":\"ReplacingMergeTreeEngine_ClickHouse:Engine\",\"OrderBy\":null,\"PartitionBy\":null,\"PrimaryKey\":null,\"SampleBy\":null,\"Settings\":{\"IndexGranularity\":8192,\"IndexGranularityBytes\":10485760,\"MinIndexGranularityBytes\":1024,\"EnableMixedGranularityParts\":false,\"UseMinimalisticPartHeaderInZookeeper\":false,\"MinMergeBytesToUseDirectIo\":10737418240,\"MergeWithTtlTimeout\":\"1.00:00:00\",\"WriteFinalMark\":false,\"MergeMaxBlockSize\":8192,\"StoragePolicy\":null,\"MinBytesForWidePart\":null,\"MinRowsForWidePart\":null,\"MaxPartsInTotal\":null,\"MaxCompressBlockSize\":null,\"MinCompressBlockSize\":null,\"IsDefault\":true}}");
                });

            modelBuilder.Entity("EntityFrameworkCore.ClickHouse.TestCases.aa", b =>
                {
                    b.Property<int>("a")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int32");

                    b.HasKey("a");

                    b.ToTable("aa");

                    b.HasAnnotation("PostgreSQLEngine_ClickHouse:Engine", "{\"EngineType\":\"PostgreSQLEngine_ClickHouse:Engine\",\"Table\":\"aa\",\"Schema\":null}");
                });
#pragma warning restore 612, 618
        }
    }
}
