// <auto-generated />
using System;
using CHUseCases.Infra;
using ClickHouse.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CHUseCases.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240506112703_another")]
    partial class another
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("CHUseCases.Infra.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int32");

                    b.Property<int>("Count")
                        .HasColumnType("Int32");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime");

                    b.Property<int>("UserId")
                        .HasColumnType("Int32");

                    b.HasKey("Id");

                    b.ToTable("Balances");

                    b
                        .HasAnnotation("ClickHouseTableAttribute", "CREATE_OR_REPLACE")
                        .HasAnnotation("ReplacingMergeTreeEngine_ClickHouse:Engine", "{\"EngineType\":\"ReplacingMergeTreeEngine_ClickHouse:Engine\",\"OrderBy\":null,\"PartitionBy\":\"toYYYYMM(Date)\",\"PrimaryKey\":\"Id\",\"SampleBy\":null,\"Settings\":{\"IndexGranularity\":8192,\"IndexGranularityBytes\":10485760,\"MinIndexGranularityBytes\":1024,\"EnableMixedGranularityParts\":false,\"UseMinimalisticPartHeaderInZookeeper\":false,\"MinMergeBytesToUseDirectIo\":10737418240,\"MergeWithTtlTimeout\":\"1.00:00:00\",\"WriteFinalMark\":false,\"MergeMaxBlockSize\":8192,\"StoragePolicy\":null,\"MinBytesForWidePart\":null,\"MinRowsForWidePart\":null,\"MaxPartsInTotal\":null,\"MaxCompressBlockSize\":null,\"MinCompressBlockSize\":null,\"IsDefault\":true}}");
                });

            modelBuilder.Entity("CHUseCases.Infra.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int32");

                    b.Property<int>("Count")
                        .HasColumnType("Int32");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("String");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b
                        .HasAnnotation("ClickHouseTableAttribute", "CREATE_OR_REPLACE")
                        .HasAnnotation("ReplacingMergeTreeEngine_ClickHouse:Engine", "{\"EngineType\":\"ReplacingMergeTreeEngine_ClickHouse:Engine\",\"OrderBy\":null,\"PartitionBy\":null,\"PrimaryKey\":\"Id\",\"SampleBy\":null,\"Settings\":{\"IndexGranularity\":8192,\"IndexGranularityBytes\":10485760,\"MinIndexGranularityBytes\":1024,\"EnableMixedGranularityParts\":false,\"UseMinimalisticPartHeaderInZookeeper\":false,\"MinMergeBytesToUseDirectIo\":10737418240,\"MergeWithTtlTimeout\":\"1.00:00:00\",\"WriteFinalMark\":false,\"MergeMaxBlockSize\":8192,\"StoragePolicy\":null,\"MinBytesForWidePart\":null,\"MinRowsForWidePart\":null,\"MaxPartsInTotal\":null,\"MaxCompressBlockSize\":null,\"MinCompressBlockSize\":null,\"IsDefault\":true}}");
                });

            modelBuilder.Entity("CHUseCases.Infra.Balance", b =>
                {
                    b.HasOne("CHUseCases.Infra.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
